export KBUILD_VERBOSE=1 
export ARCH=arm64
obj-m := hantrodriver.o
hantrodriver-objs = hantro_drv.o hx280enc.o hantrodec.o hantro_fence.o hantrocache.o hantro_mmu.o hantro_vcmd.o hantro_vcmd_slice.o vcmdswhwregisters.o bidirect_list.o devicemgr.o hantro_dmabuf.o hantro_fs.o hantro_drm.o hantro_dec400.o hantro_cache.o
KDIR := /home/vsi/jam/NXP865/k510/linux-imx
PWD := $(shell pwd)
default:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean::
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	-rm -f .version
